const bcrypt = require('bcryptjs');
const db = require('../config/database');
const { createTables } = require('./schema');

function seedDatabase() {
  console.log('Creating tables...');
  createTables();

  console.log('Seeding database...');

  const userCount = db.prepare('SELECT COUNT(*) as count FROM users').get().count;
  if (userCount > 0) {
    console.log('Database already seeded. Skipping...');
    return;
  }

  const hashedPassword = bcrypt.hashSync('password123', 10);

  const users = [
    { name: 'Admin User', email: 'admin@travelportal.com', password: bcrypt.hashSync('admin123', 10), role: 'admin', avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150', phone: '+1-555-0100', bio: 'Platform administrator with 10+ years in travel industry', location: 'New York, USA' },
    { name: 'Sarah Johnson', email: 'sarah@email.com', password: hashedPassword, role: 'user', avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150', phone: '+1-555-0101', bio: 'Travel enthusiast exploring the world one city at a time', location: 'Los Angeles, USA' },
    { name: 'Michael Chen', email: 'michael@email.com', password: hashedPassword, role: 'user', avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150', phone: '+1-555-0102', bio: 'Adventure seeker and photography lover', location: 'San Francisco, USA' },
    { name: 'Emma Williams', email: 'emma@email.com', password: hashedPassword, role: 'user', avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150', phone: '+1-555-0103', bio: 'Foodie traveler always looking for local cuisines', location: 'London, UK' },
    { name: 'James Brown', email: 'james@email.com', password: hashedPassword, role: 'user', avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150', phone: '+1-555-0104', bio: 'History buff and cultural explorer', location: 'Boston, USA' },
    { name: 'Olivia Davis', email: 'olivia@email.com', password: hashedPassword, role: 'user', avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150', phone: '+1-555-0105', bio: 'Beach lover and scuba diving enthusiast', location: 'Miami, USA' },
    { name: 'William Martinez', email: 'william@email.com', password: hashedPassword, role: 'user', avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150', phone: '+1-555-0106', bio: 'Mountain hiking and nature photography', location: 'Denver, USA' },
    { name: 'Sophia Anderson', email: 'sophia@email.com', password: hashedPassword, role: 'user', avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150', phone: '+1-555-0107', bio: 'Luxury travel and boutique hotels', location: 'Paris, France' },
    { name: 'Lucas Taylor', email: 'lucas@email.com', password: hashedPassword, role: 'user', avatar: 'https://images.unsplash.com/photo-1519345182560-3f2917c472ef?w=150', phone: '+1-555-0108', bio: 'Backpacking and budget travel expert', location: 'Berlin, Germany' },
    { name: 'Ava Thomas', email: 'ava@email.com', password: hashedPassword, role: 'user', avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150', phone: '+1-555-0109', bio: 'Solo female traveler and blogger', location: 'Tokyo, Japan' },
    { name: 'Noah Garcia', email: 'noah@email.com', password: hashedPassword, role: 'user', avatar: 'https://images.unsplash.com/photo-1463453091185-61582044d556?w=150', phone: '+1-555-0110', bio: 'Road trip enthusiast and camper', location: 'Austin, USA' },
    { name: 'Isabella Rodriguez', email: 'isabella@email.com', password: hashedPassword, role: 'user', avatar: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=150', phone: '+1-555-0111', bio: 'Art and architecture lover', location: 'Barcelona, Spain' },
    { name: 'Mason Lee', email: 'mason@email.com', password: hashedPassword, role: 'user', avatar: 'https://images.unsplash.com/photo-1504257432389-52343af06ae3?w=150', phone: '+1-555-0112', bio: 'Digital nomad working from exotic locations', location: 'Bali, Indonesia' },
    { name: 'Mia Wilson', email: 'mia@email.com', password: hashedPassword, role: 'user', avatar: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=150', phone: '+1-555-0113', bio: 'Wellness and retreat traveler', location: 'Sydney, Australia' },
    { name: 'Ethan Harris', email: 'ethan@email.com', password: hashedPassword, role: 'user', avatar: 'https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?w=150', phone: '+1-555-0114', bio: 'Adventure sports and extreme activities', location: 'Queenstown, NZ' },
    { name: 'Charlotte Clark', email: 'charlotte@email.com', password: hashedPassword, role: 'user', avatar: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=150', phone: '+1-555-0115', bio: 'Cruise and ocean voyage lover', location: 'Vancouver, Canada' },
    { name: 'Alexander Lewis', email: 'alexander@email.com', password: hashedPassword, role: 'user', avatar: 'https://images.unsplash.com/photo-1509967419530-da38b4704bc6?w=150', phone: '+1-555-0116', bio: 'Safari and wildlife photography', location: 'Nairobi, Kenya' },
    { name: 'Amelia Walker', email: 'amelia@email.com', password: hashedPassword, role: 'user', avatar: 'https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?w=150', phone: '+1-555-0117', bio: 'Cultural immersion and language learning', location: 'Rome, Italy' },
    { name: 'Daniel Hall', email: 'daniel@email.com', password: hashedPassword, role: 'user', avatar: 'https://images.unsplash.com/photo-1521119989659-a83eee488058?w=150', phone: '+1-555-0118', bio: 'City breaks and urban exploration', location: 'Chicago, USA' },
    { name: 'Harper Allen', email: 'harper@email.com', password: hashedPassword, role: 'user', avatar: 'https://images.unsplash.com/photo-1544723795-3fb6469f5b39?w=150', phone: '+1-555-0119', bio: 'Eco-tourism and sustainable travel advocate', location: 'Stockholm, Sweden' }
  ];

  const insertUser = db.prepare('INSERT INTO users (name, email, password, role, avatar, phone, bio, location) VALUES (?, ?, ?, ?, ?, ?, ?, ?)');
  users.forEach(user => insertUser.run(user.name, user.email, user.password, user.role, user.avatar, user.phone, user.bio, user.location));
  console.log(`Inserted ${users.length} users`);

  const destinations = [
    { name: 'Santorini Sunset Villas', country: 'Greece', city: 'Santorini', description: 'Experience breathtaking sunsets from your private villa overlooking the caldera. White-washed architecture, infinity pools, and world-class Mediterranean cuisine await in this romantic Greek island paradise.', images: JSON.stringify(['https://images.unsplash.com/photo-1613395877344-13d4c79e4284?w=800']), gallery: JSON.stringify(['https://images.unsplash.com/photo-1613395877344-13d4c79e4284?w=400', 'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?w=400', 'https://images.unsplash.com/photo-1602343168117-bb8ffe3e2e9f?w=400']), price: 2499, duration: 7, rating: 4.8, weather: 'Sunny, 28°C', category: 'beach', activities: JSON.stringify(['Sunset Viewing', 'Wine Tasting', 'Boat Tours', 'Volcano Hiking', 'Photography']), latitude: 36.3932, longitude: 25.4615, featured: 1, popular: 1 },
    { name: 'Maldives Overwater Escape', country: 'Maldives', city: 'Male Atoll', description: 'Stay in luxurious overwater bungalows surrounded by crystal-clear turquoise waters. World-class snorkeling, private butler service, and pristine white sand beaches create the ultimate tropical getaway.', images: JSON.stringify(['https://images.unsplash.com/photo-1514282401047-d79a71a590e8?w=800']), gallery: JSON.stringify(['https://images.unsplash.com/photo-1514282401047-d79a71a590e8?w=400', 'https://images.unsplash.com/photo-1573843981267-be1999ff37cd?w=400', 'https://images.unsplash.com/photo-1590523741831-ab7e8b8f9c7f?w=400']), price: 3899, duration: 5, rating: 4.9, weather: 'Tropical, 30°C', category: 'beach', activities: JSON.stringify(['Snorkeling', 'Diving', 'Spa Treatments', 'Sunset Cruise', 'Water Sports']), latitude: 4.1755, longitude: 73.5093, featured: 1, popular: 1 },
    { name: 'Swiss Alps Ski Retreat', country: 'Switzerland', city: 'Zermatt', description: 'World-class skiing beneath the iconic Matterhorn peak. Luxury chalets with fireplaces, gourmet dining, and après-ski experiences in this charming car-free alpine village.', images: JSON.stringify(['https://images.unsplash.com/photo-1552423316-682f1214c554?w=800']), gallery: JSON.stringify(['https://images.unsplash.com/photo-1552423316-682f1214c554?w=400', 'https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99?w=400', 'https://images.unsplash.com/photo-1551524559-8af4e6624178?w=400']), price: 3299, duration: 6, rating: 4.7, weather: 'Snowy, -2°C', category: 'mountain', activities: JSON.stringify(['Skiing', 'Snowboarding', 'Spa & Wellness', 'Gourmet Dining', 'Scenic Train Rides']), latitude: 46.0207, longitude: 7.7491, featured: 1, popular: 1 },
    { name: 'Kyoto Temple Gardens', country: 'Japan', city: 'Kyoto', description: 'Immerse yourself in ancient Japanese culture among thousands of vermilion torii gates, serene zen gardens, and traditional tea houses. Experience cherry blossoms in spring and vibrant autumn foliage.', images: JSON.stringify(['https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=800']), gallery: JSON.stringify(['https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=400', 'https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=400', 'https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=400']), price: 1899, duration: 8, rating: 4.8, weather: 'Mild, 18°C', category: 'cultural', activities: JSON.stringify(['Temple Visits', 'Tea Ceremony', 'Kimono Experience', 'Bamboo Forest Walk', 'Cooking Class']), latitude: 35.0116, longitude: 135.7681, featured: 1, popular: 1 },
    { name: 'Safari Lodge Experience', country: 'Kenya', city: 'Masai Mara', description: 'Witness the Big Five on daily game drives across the vast savannah. Luxury tented camps, Maasai village visits, and the spectacular Great Migration make this an unforgettable African adventure.', images: JSON.stringify(['https://images.unsplash.com/photo-1516426122078-c23e76319801?w=800']), gallery: JSON.stringify(['https://images.unsplash.com/photo-1516426122078-c23e76319801?w=400', 'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=400', 'https://images.unsplash.com/photo-1518457607834-6e8d80c183c5?w=400']), price: 4599, duration: 6, rating: 4.9, weather: 'Warm, 25°C', category: 'adventure', activities: JSON.stringify(['Game Drives', 'Hot Air Balloon', 'Maasai Village Visit', 'Bush Walks', 'Photography Safari']), latitude: -1.4061, longitude: 35.1858, featured: 1, popular: 1 },
    { name: 'Amalfi Coast Luxury', country: 'Italy', city: 'Positano', description: 'Dramatic cliffs, colorful villages cascading to the sea, and the finest Italian cuisine. Explore hidden coves by boat, visit historic Ravello, and savor limoncello on your terrace overlooking the Mediterranean.', images: JSON.stringify(['https://images.unsplash.com/photo-1534113414509-0eec2bfb493f?w=800']), gallery: JSON.stringify(['https://images.unsplash.com/photo-1534113414509-0eec2bfb493f?w=400', 'https://images.unsplash.com/photo-1516483638261-f4dbaf036963?w=400', 'https://images.unsplash.com/photo-1523531294919-4bcd7c65e216?w=400']), price: 2799, duration: 7, rating: 4.7, weather: 'Sunny, 26°C', category: 'beach', activities: JSON.stringify(['Boat Tours', 'Cooking Classes', 'Hiking', 'Wine Tasting', 'Shopping']), latitude: 40.6281, longitude: 14.4850, featured: 1, popular: 1 },
    { name: 'Bali Rice Terrace Haven', country: 'Indonesia', city: 'Ubud', description: 'Find your zen among emerald rice terraces, ancient temples, and lush jungles. Yoga retreats, traditional Balinese spa treatments, and vibrant arts scene make Ubud a sanctuary for the soul.', images: JSON.stringify(['https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800']), gallery: JSON.stringify(['https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=400', 'https://images.unsplash.com/photo-1555400038-63f5ba517a47?w=400', 'https://images.unsplash.com/photo-1518548419970-58e3b4079ab2?w=400']), price: 1299, duration: 8, rating: 4.6, weather: 'Tropical, 27°C', category: 'cultural', activities: JSON.stringify(['Yoga & Meditation', 'Rice Terrace Walk', 'Temple Visits', 'Cooking Class', 'Spa Treatment']), latitude: -8.5069, longitude: 115.2625, featured: 0, popular: 1 },
    { name: 'Northern Lights Lodge', country: 'Iceland', city: 'Reykjavik', description: 'Chase the aurora borealis from geothermal hot springs and glass igloos. Explore glaciers, volcanic landscapes, and thundering waterfalls in the land of fire and ice.', images: JSON.stringify(['https://images.unsplash.com/photo-1531366936337-7c912a4589a7?w=800']), gallery: JSON.stringify(['https://images.unsplash.com/photo-1531366936337-7c912a4589a7?w=400', 'https://images.unsplash.com/photo-1520769945061-0a448c463865?w=400', 'https://images.unsplash.com/photo-1504829857797-ddff29c27927?w=400']), price: 2199, duration: 5, rating: 4.8, weather: 'Cold, 2°C', category: 'adventure', activities: JSON.stringify(['Northern Lights Hunt', 'Hot Springs', 'Glacier Hiking', 'Whale Watching', 'Golden Circle Tour']), latitude: 64.1466, longitude: -21.9426, featured: 0, popular: 1 },
    { name: 'Marrakech Riad Palace', country: 'Morocco', city: 'Marrakech', description: 'Lose yourself in the labyrinthine medina, stay in a beautifully restored riad, and experience vibrant souks, ornate palaces, and the magic of Moroccan hospitality.', images: JSON.stringify(['https://images.unsplash.com/photo-1597212618440-806262de4f6b?w=800']), gallery: JSON.stringify(['https://images.unsplash.com/photo-1597212618440-806262de4f6b?w=400', 'https://images.unsplash.com/photo-1489749798305-4fea3ae63d43?w=400', 'https://images.unsplash.com/photo-1548018560-c507095699f1?w=400']), price: 1599, duration: 6, rating: 4.5, weather: 'Warm, 22°C', category: 'cultural', activities: JSON.stringify(['Medina Tour', 'Cooking Class', 'Hammam Spa', 'Desert Excursion', 'Souk Shopping']), latitude: 31.6295, longitude: -7.9811, featured: 0, popular: 1 },
    { name: 'Great Barrier Reef Dive', country: 'Australia', city: 'Cairns', description: 'Explore the world\'s largest coral reef system with expert marine biologists. Luxury liveaboard diving, pristine beaches, and encounters with sea turtles, sharks, and vibrant coral gardens.', images: JSON.stringify(['https://images.unsplash.com/photo-1582967788606-a171c1080cb0?w=800']), gallery: JSON.stringify(['https://images.unsplash.com/photo-1582967788606-a171c1080cb0?w=400', 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=400', 'https://images.unsplash.com/photo-1682687220742-aba13b6e50ba?w=400']), price: 2899, duration: 6, rating: 4.7, weather: 'Tropical, 29°C', category: 'beach', activities: JSON.stringify(['Scuba Diving', 'Snorkeling', 'Glass Bottom Boat', 'Island Hopping', 'Marine Life Tour']), latitude: -16.9186, longitude: 145.7781, featured: 0, popular: 1 },
    { name: 'Patagonia Wilderness Trek', country: 'Argentina', city: 'El Calafate', description: 'Trek across glaciers, turquoise lakes, and dramatic granite peaks in one of the world\'s last true wilderness areas. Expert guides lead you through Torres del Paine and Perito Moreno Glacier.', images: JSON.stringify(['https://images.unsplash.com/photo-1531761535209-180857e963b9?w=800']), gallery: JSON.stringify(['https://images.unsplash.com/photo-1531761535209-180857e963b9?w=400', 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=400', 'https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=400']), price: 3299, duration: 9, rating: 4.8, weather: 'Cool, 12°C', category: 'mountain', activities: JSON.stringify(['Glacier Trekking', 'Wildlife Spotting', 'Camping', 'Photography', 'Kayaking']), latitude: -50.3370, longitude: -72.2648, featured: 0, popular: 1 },
    { name: 'Venetian Canal Palazzo', country: 'Italy', city: 'Venice', description: 'Stay in a historic palazzo on the Grand Canal. Gondola rides, masked balls, and Michelin-starred dining in the world\'s most romantic floating city.', images: JSON.stringify(['https://images.unsplash.com/photo-1514890547357-a9ee288728e0?w=800']), gallery: JSON.stringify(['https://images.unsplash.com/photo-1514890547357-a9ee288728e0?w=400', 'https://images.unsplash.com/photo-1523906834658-6e24ef2386f9?w=400', 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=400']), price: 2399, duration: 5, rating: 4.6, weather: 'Mild, 20°C', category: 'cultural', activities: JSON.stringify(['Gondola Ride', 'Murano Glass Tour', 'Cooking Class', 'Art Gallery Visit', 'Wine Tasting']), latitude: 45.4408, longitude: 12.3155, featured: 0, popular: 1 },
    { name: 'Bora Bora Pearl Resort', country: 'French Polynesia', city: 'Bora Bora', description: 'The ultimate honeymoon destination with overwater villas, Mount Otemanu views, and crystal-clear lagoons perfect for swimming with tropical fish and rays.', images: JSON.stringify(['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800']), gallery: JSON.stringify(['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=400', 'https://images.unsplash.com/photo-1589197331516-4d84b72ebde3?w=400', 'https://images.unsplash.com/photo-1542259659-4ab34f7d97ad?w=400']), price: 4299, duration: 6, rating: 4.9, weather: 'Tropical, 28°C', category: 'beach', activities: JSON.stringify(['Lagoon Swimming', 'Mount Otemanu Hike', 'Polynesian Feast', 'Snorkeling', 'Jet Ski Tour']), latitude: -16.5004, longitude: -151.7415, featured: 0, popular: 1 },
    { name: 'Machu Picchu Expedition', country: 'Peru', city: 'Cusco', description: 'Trek the Inca Trail to the lost city in the clouds. Explore Sacred Valley ruins, vibrant markets, and experience authentic Andean culture at high altitude.', images: JSON.stringify(['https://images.unsplash.com/photo-1587595431973-160d0d94add1?w=800']), gallery: JSON.stringify(['https://images.unsplash.com/photo-1587595431973-1600d0d94add1?w=400', 'https://images.unsplash.com/photo-1526392060635-9d6019884377?w=400', 'https://images.unsplash.com/photo-1580619305218-8423a7ef79b4?w=400']), price: 2199, duration: 7, rating: 4.8, weather: 'Mild, 15°C', category: 'adventure', activities: JSON.stringify(['Inca Trail Trek', 'Sacred Valley Tour', 'Cusco Exploration', 'Local Market Visit', 'Cooking Class']), latitude: -13.1631, longitude: -72.5450, featured: 0, popular: 1 },
    { name: 'Dubai Desert Oasis', country: 'UAE', city: 'Dubai', description: 'Experience ultra-luxury in the desert metropolis. Burj Khalifa views, desert safaris, gold souks, and world-class shopping blend tradition with futuristic opulence.', images: JSON.stringify(['https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=800']), gallery: JSON.stringify(['https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=400', 'https://images.unsplash.com/photo-1518684079-3c830dcef090?w=400', 'https://images.unsplash.com/photo-1546412414-e1885259563a?w=400']), price: 3499, duration: 5, rating: 4.7, weather: 'Hot, 35°C', category: 'luxury', activities: JSON.stringify(['Desert Safari', 'Burj Khalifa Visit', 'Shopping', 'Dhow Cruise', 'Spa Treatment']), latitude: 25.2048, longitude: 55.2708, featured: 0, popular: 1 },
    { name: 'Petra Ancient City', country: 'Jordan', city: 'Wadi Musa', description: 'Walk through the Siq to discover the rose-red city carved into cliffs. Bedouin hospitality, Dead Sea floating, and Wadi Rum desert camping complete this Middle Eastern gem.', images: JSON.stringify(['https://images.unsplash.com/photo-1579606038868-32d2726d3944?w=800']), gallery: JSON.stringify(['https://images.unsplash.com/photo-1579606038868-32d2726d3944?w=400', 'https://images.unsplash.com/photo-1546536660-d163f3ba6f09?w=400', 'https://images.unsplash.com/photo-1501232060322-aa87215ab531?w=400']), price: 1899, duration: 6, rating: 4.8, weather: 'Warm, 24°C', category: 'cultural', activities: JSON.stringify(['Petra Treasury Visit', 'Wadi Rum Camping', 'Dead Sea Float', 'Bedouin Dinner', 'Archaeological Tour']), latitude: 30.3285, longitude: 35.4444, featured: 0, popular: 1 },
    { name: 'Queenstown Adventure Hub', country: 'New Zealand', city: 'Queenstown', description: 'The adventure capital of the world offers bungee jumping, skydiving, jet boating, and world-class skiing. Stunning lake and mountain scenery at every turn.', images: JSON.stringify(['https://images.unsplash.com/photo-1507699622108-4be3abd695ad?w=800']), gallery: JSON.stringify(['https://images.unsplash.com/photo-1507699622108-4be3abd695ad?w=400', 'https://images.unsplash.com/photo-1589802829985-817e51171b92?w=400', 'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=400']), price: 2599, duration: 7, rating: 4.7, weather: 'Cool, 14°C', category: 'adventure', activities: JSON.stringify(['Bungee Jumping', 'Skydiving', 'Jet Boating', 'Skiing', 'Wine Tour']), latitude: -45.0312, longitude: 168.6626, featured: 0, popular: 0 },
    { name: 'Seychelles Island Paradise', country: 'Seychelles', city: 'Mahe', description: 'Pristine beaches with granite boulders, giant tortoises, and rare bird species. Exclusive island-hopping, snorkeling in marine parks, and Creole cuisine.', images: JSON.stringify(['https://images.unsplash.com/photo-1559128010-7c1ad6e1b6a5?w=800']), gallery: JSON.stringify(['https://images.unsplash.com/photo-1559128010-7c1ad6e1b6a5?w=400', 'https://images.unsplash.com/photo-1590523741831-ab7e8b8f9c7f?w=400', 'https://images.unsplash.com/photo-1516815231560-8f41ec531527?w=400']), price: 3799, duration: 6, rating: 4.8, weather: 'Tropical, 27°C', category: 'beach', activities: JSON.stringify(['Island Hopping', 'Snorkeling', 'Nature Walk', 'Creole Cooking', 'Giant Tortoise Visit']), latitude: -4.6796, longitude: 55.4920, featured: 0, popular: 0 },
    { name: 'Banff Mountain Lodge', country: 'Canada', city: 'Banff', description: ' turquoise lakes, snow-capped peaks, and abundant wildlife in Canada\'s oldest national park. Canoeing on Lake Louise, hot springs, and cozy mountain lodges.', images: JSON.stringify(['https://images.unsplash.com/photo-1503614472-8c93d56e92ce?w=800']), gallery: JSON.stringify(['https://images.unsplash.com/photo-1503614472-8c93d56e92ce?w=400', 'https://images.unsplash.com/photo-1561134643-663d3d7a81b6?w=400', 'https://images.unsplash.com/photo-1588598198321-9735fd52455b?w=400']), price: 2299, duration: 6, rating: 4.7, weather: 'Cool, 10°C', category: 'mountain', activities: JSON.stringify(['Lake Louise Canoe', 'Hot Springs', 'Wildlife Tour', 'Hiking', 'Skiing']), latitude: 51.1784, longitude: -115.5708, featured: 0, popular: 0 },
    { name: 'St. Petersburg Palace Tour', country: 'Russia', city: 'St. Petersburg', description: 'Marvel at the Winter Palace, Hermitage Museum, and opulent cathedrals. White Nights river cruises, ballet performances, and imperial Russian grandeur.', images: JSON.stringify(['https://images.unsplash.com/photo-1556610961-2fecc592bcb4?w=800']), gallery: JSON.stringify(['https://images.unsplash.com/photo-1556610961-2fecc592bcb4?w=400', 'https://images.unsplash.com/photo-1524230507669-5ff97982bb5e?w=400', 'https://images.unsplash.com/photo-1547448415-e9f5b28e570d?w=400']), price: 1999, duration: 6, rating: 4.5, weather: 'Cool, 12°C', category: 'cultural', activities: JSON.stringify(['Hermitage Museum', 'Ballet Performance', 'Canal Cruise', 'Church Tour', 'Faberge Museum']), latitude: 59.9311, longitude: 30.3609, featured: 0, popular: 0 },
    { name: 'Fiji Island Retreat', country: 'Fiji', city: 'Nadi', description: 'Warm Fijian hospitality, pristine coral reefs, and palm-fringed beaches. Kava ceremonies, waterfall hikes, and world-class diving in the Soft Coral Capital.', images: JSON.stringify(['https://images.unsplash.com/photo-1542259659-4ab34f7d97ad?w=800']), gallery: JSON.stringify(['https://images.unsplash.com/photo-1542259659-4ab34f7d97ad?w=400', 'https://images.unsplash.com/photo-1596895111956-bf1cf0599ce5?w=400', 'https://images.unsplash.com/photo-1516815231560-8f41ec531527?w=400']), price: 2899, duration: 7, rating: 4.7, weather: 'Tropical, 26°C', category: 'beach', activities: JSON.stringify(['Diving', 'Village Visit', 'Waterfall Hike', 'Kava Ceremony', 'Island Hopping']), latitude: -17.7765, longitude: 177.4356, featured: 0, popular: 0 },
    { name: 'Cappadocia Hot Air Balloons', country: 'Turkey', city: 'Goreme', description: 'Float above fairy chimneys and cave dwellings at sunrise. Underground cities, pottery workshops, and Turkish baths in this otherworldly landscape.', images: JSON.stringify(['https://images.unsplash.com/photo-1641128324972-af3212f0f6bd?w=800']), gallery: JSON.stringify(['https://images.unsplash.com/photo-1641128324972-af3212f0f6bd?w=400', 'https://images.unsplash.com/photo-1527838832700-5059252407fa?w=400', 'https://images.unsplash.com/photo-1545063914-818571411569?w=400']), price: 1499, duration: 5, rating: 4.6, weather: 'Mild, 19°C', category: 'adventure', activities: JSON.stringify(['Hot Air Balloon', 'Cave Hotel Stay', 'Underground City', 'Pottery Workshop', 'Turkish Bath']), latitude: 38.6431, longitude: 34.8290, featured: 0, popular: 0 },
    { name: 'Hawaii Volcano Adventure', country: 'USA', city: 'Kailua-Kona', description: 'Witness active volcanoes, black sand beaches, and tropical rainforests. Snorkel with manta rays, attend a luau, and drive to the summit of Mauna Kea.', images: JSON.stringify(['https://images.unsplash.com/photo-1542259011435-15fbf604c73a?w=800']), gallery: JSON.stringify(['https://images.unsplash.com/photo-1542259011435-15fbf604c73a?w=400', 'https://images.unsplash.com/photo-1558244409-4627f6cfac5d?w=400', 'https://images.unsplash.com/photo-1590333748338-d629e4564ad9?w=400']), price: 2699, duration: 7, rating: 4.7, weather: 'Tropical, 25°C', category: 'beach', activities: JSON.stringify(['Volcano Tour', 'Manta Ray Snorkel', 'Luau', 'Mauna Kea Summit', 'Coffee Plantation']), latitude: 19.6398, longitude: -155.9969, featured: 0, popular: 0 },
    { name: 'Swedish Lapland Igloos', country: 'Sweden', city: 'Kiruna', description: 'Sleep under the Northern Lights in glass igloos. Dog sledding, ice hotel visits, Sami culture encounters, and snowmobiling in Arctic wilderness.', images: JSON.stringify(['https://images.unsplash.com/photo-1531366936337-7c912a4589a7?w=800']), gallery: JSON.stringify(['https://images.unsplash.com/photo-1531366936337-7c912a4589a7?w=400', 'https://images.unsplash.com/photo-1518182170546-0766bc6f9213?w=400', 'https://images.unsplash.com/photo-1483347756197-71ef80e95f73?w=400']), price: 3199, duration: 5, rating: 4.8, weather: 'Freezing, -10°C', category: 'adventure', activities: JSON.stringify(['Glass Igloo Stay', 'Dog Sledding', 'Ice Hotel Visit', 'Snowmobiling', 'Aurora Hunting']), latitude: 67.8558, longitude: 20.2253, featured: 0, popular: 0 },
    { name: 'Santorini Wine Country', country: 'Greece', city: 'Oia', description: 'Explore volcanic vineyards and taste unique Assyrtiko wines. Cliffside dining, caldera yacht cruises, and the most photographed sunset in the world.', images: JSON.stringify(['https://images.unsplash.com/photo-1613395877344-13d4c79e4284?w=800']), gallery: JSON.stringify(['https://images.unsplash.com/photo-1613395877344-13d4c79e4284?w=400', 'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?w=400', 'https://images.unsplash.com/photo-1602343168117-bb8ffe3e2e9f?w=400']), price: 2299, duration: 6, rating: 4.7, weather: 'Sunny, 27°C', category: 'luxury', activities: JSON.stringify(['Wine Tasting', 'Sunset Cruise', 'Cooking Class', 'Photography Tour', 'Caldera Hike']), latitude: 36.4618, longitude: 25.3753, featured: 0, popular: 0 },
    { name: 'Rio Carnival Experience', country: 'Brazil', city: 'Rio de Janeiro', description: 'Samba dancing, Christ the Redeemer, Sugarloaf Mountain, and the world\'s most famous beach - Copacabana. Experience the energy and warmth of Brazilian culture.', images: JSON.stringify(['https://images.unsplash.com/photo-1483729558449-99ef09a8c325?w=800']), gallery: JSON.stringify(['https://images.unsplash.com/photo-1483729558449-99ef09a8c325?w=400', 'https://images.unsplash.com/photo-1593995863951-57ced974c91d?w=400', 'https://images.unsplash.com/photo-1551983156-7b02c74d7e6b?w=400']), price: 1999, duration: 6, rating: 4.6, weather: 'Warm, 28°C', category: 'cultural', activities: JSON.stringify(['Christ the Redeemer', 'Samba Show', 'Sugarloaf Mountain', 'Copacabana Beach', 'Favela Tour']), latitude: -22.9068, longitude: -43.1729, featured: 0, popular: 0 },
    { name: 'Zanzibar Spice Island', country: 'Tanzania', city: 'Stone Town', description: 'White sand beaches, spice plantations, and a UNESCO World Heritage old town. Dolphin watching, prison island visits, and Swahili culinary experiences.', images: JSON.stringify(['https://images.unsplash.com/photo-1590523741831-ab7e8b8f9c7f?w=800']), gallery: JSON.stringify(['https://images.unsplash.com/photo-1590523741831-ab7e8b8f9c7f?w=400', 'https://images.unsplash.com/photo-1580060839134-75a5edca2e99?w=400', 'https://images.unsplash.com/photo-1516426122078-c23e76319801?w=400']), price: 1699, duration: 7, rating: 4.5, weather: 'Warm, 26°C', category: 'beach', activities: JSON.stringify(['Spice Tour', 'Dolphin Watching', 'Stone Town Walk', 'Prison Island', 'Swahili Cooking']), latitude: -6.1659, longitude: 39.2026, featured: 0, popular: 0 },
    { name: 'Norwegian Fjords Cruise', country: 'Norway', city: 'Bergen', description: 'Sail through dramatic fjords, past cascading waterfalls and snow-capped peaks. Flam Railway, glacier walks, and charming fishing villages.', images: JSON.stringify(['https://images.unsplash.com/photo-1506701169896-2303b922fa55?w=800']), gallery: JSON.stringify(['https://images.unsplash.com/photo-1506701169896-2303b922fa55?w=400', 'https://images.unsplash.com/photo-1513519245088-0e12902e35a6?w=400', 'https://images.unsplash.com/photo-1504829857797-ddff29c27927?w=400']), price: 2899, duration: 7, rating: 4.8, weather: 'Cool, 8°C', category: 'luxury', activities: JSON.stringify(['Fjord Cruise', 'Flam Railway', 'Glacier Walk', 'Viking History', 'Fishing Village Tour']), latitude: 60.3913, longitude: 5.3221, featured: 0, popular: 0 },
    { name: 'Taj Mahal Heritage Tour', country: 'India', city: 'Agra', description: 'Witness the iconic marble mausoleum at sunrise, explore Agra Fort, and discover Mughal architecture. Rich cuisine, bustling bazaars, and warm hospitality.', images: JSON.stringify(['https://images.unsplash.com/photo-1564507592333-c60657eea523?w=800']), gallery: JSON.stringify(['https://images.unsplash.com/photo-1564507592333-c60657eea523?w=400', 'https://images.unsplash.com/photo-1583608621157-8d24f4a20e11?w=400', 'https://images.unsplash.com/photo-1524492412937-b28074a5d7da?w=400']), price: 1299, duration: 5, rating: 4.6, weather: 'Warm, 30°C', category: 'cultural', activities: JSON.stringify(['Taj Mahal Visit', 'Agra Fort Tour', 'Local Bazaar', 'Cooking Class', 'Mohabbat Show']), latitude: 27.1751, longitude: 78.0421, featured: 0, popular: 0 },
    { name: 'Costa Rica Eco Lodge', country: 'Costa Rica', city: 'Monteverde', description: 'Zip-line through cloud forests, spot exotic wildlife, and relax in natural hot springs. A biodiversity paradise with sustainable eco-tourism practices.', images: JSON.stringify(['https://images.unsplash.com/photo-1518259102261-b40117eabbc9?w=800']), gallery: JSON.stringify(['https://images.unsplash.com/photo-1518259102261-b40117eabbc9?w=400', 'https://images.unsplash.com/photo-1590320252814-38b2d93b8560?w=400', 'https://images.unsplash.com/photo-1535591273668-578e31182c4f?w=400']), price: 1899, duration: 7, rating: 4.7, weather: 'Warm, 22°C', category: 'adventure', activities: JSON.stringify(['Zip-lining', 'Wildlife Tour', 'Hot Springs', 'Cloud Forest Walk', 'Coffee Tour']), latitude: 10.3000, longitude: -84.8000, featured: 0, popular: 0 },
    { name: 'Hanoi Street Food Tour', country: 'Vietnam', city: 'Hanoi', description: 'Navigate the chaotic Old Quarter, taste pho and banh mi from street vendors, cruise Ha Long Bay, and experience a thousand years of Vietnamese history.', images: JSON.stringify(['https://images.unsplash.com/photo-1528127269322-539801943592?w=800']), gallery: JSON.stringify(['https://images.unsplash.com/photo-1528127269322-539801943592?w=400', 'https://images.unsplash.com/photo-1528127269322-539801943592?w=400', 'https://images.unsplash.com/photo-1532375810709-75b1da00537c?w=400']), price: 1199, duration: 7, rating: 4.6, weather: 'Warm, 20°C', category: 'cultural', activities: JSON.stringify(['Street Food Tour', 'Ha Long Bay Cruise', 'Old Quarter Walk', 'Cooking Class', 'Temple Visit']), latitude: 21.0285, longitude: 105.8542, featured: 0, popular: 0 },
    { name: 'Cinque Terre Coastal Walk', country: 'Italy', city: 'Manarola', description: 'Hike between five colorful fishing villages perched on the rugged Italian Riviera. Fresh seafood, local wine, and breathtaking Mediterranean views.', images: JSON.stringify(['https://images.unsplash.com/photo-1516483638261-f4dbaf036963?w=800']), gallery: JSON.stringify(['https://images.unsplash.com/photo-1516483638261-f4dbaf036963?w=400', 'https://images.unsplash.com/photo-1523531294919-4bcd7c65e216?w=400', 'https://images.unsplash.com/photo-1534113414509-0eec2bfb493f?w=400']), price: 1799, duration: 5, rating: 4.7, weather: 'Mild, 22°C', category: 'beach', activities: JSON.stringify(['Coastal Hike', 'Wine Tasting', 'Seafood Dinner', 'Village Exploration', 'Boat Tour']), latitude: 44.1067, longitude: 9.7262, featured: 0, popular: 0 },
    { name: 'Uluru Outback Journey', country: 'Australia', city: 'Yulara', description: 'Stand in awe before the massive red monolith at sunrise and sunset. Learn about Aboriginal culture, stargaze in the desert, and explore Kata Tjuta.', images: JSON.stringify(['https://images.unsplash.com/photo-1529108190281-9a4f620bc2d8?w=800']), gallery: JSON.stringify(['https://images.unsplash.com/photo-1529108190281-9a4f620bc2d8?w=400', 'https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?w=400', 'https://images.unsplash.com/photo-1551009175-8a68da93d5f9?w=400']), price: 2399, duration: 4, rating: 4.8, weather: 'Hot, 32°C', category: 'adventure', activities: JSON.stringify(['Uluru Sunrise', 'Aboriginal Tour', 'Desert Stargazing', 'Kata Tjuta Hike', 'Sounds of Silence Dinner']), latitude: -25.3444, longitude: 131.0369, featured: 0, popular: 0 }
  ];

  const insertDest = db.prepare(`INSERT INTO destinations 
    (name, country, city, description, images, gallery, price, duration, rating, weather, category, activities, latitude, longitude, featured, popular) 
    VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`);
  
  destinations.forEach(d => {
    insertDest.run(d.name, d.country, d.city, d.description, d.images, d.gallery, d.price, d.duration, d.rating, d.weather, d.category, d.activities, d.latitude, d.longitude, d.featured, d.popular);
  });
  console.log(`Inserted ${destinations.length} destinations`);

  const guides = [
    { name: 'Elena Papadopoulos', avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150', email: 'elena@guides.com', phone: '+30-555-0201', bio: 'Archaeologist and historian with 15 years experience leading tours across Greece. Specializes in ancient history and Mediterranean cuisine.', experience: 15, languages: JSON.stringify(['English', 'Greek', 'Italian', 'French']), specialties: JSON.stringify(['Ancient History', 'Food Tours', 'Island Hopping']), rating: 4.9, review_count: 127, location: 'Athens, Greece', price_per_day: 250, available: 1 },
    { name: 'Kenji Tanaka', avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150', email: 'kenji@guides.com', phone: '+81-555-0202', bio: 'Third-generation tea master and cultural ambassador. Offers unique insights into Japanese traditions, from zen gardens to modern Tokyo culture.', experience: 12, languages: JSON.stringify(['English', 'Japanese', 'Mandarin']), specialties: JSON.stringify(['Tea Ceremony', 'Temples', 'Culinary Arts']), rating: 4.8, review_count: 98, location: 'Kyoto, Japan', price_per_day: 220, available: 1 },
    { name: 'Marco Rossi', avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150', email: 'marco@guides.com', phone: '+39-555-0203', bio: 'Born and raised in Rome, Marco is a certified sommelier and art historian. His food and wine tours reveal the hidden gems of Italian culture.', experience: 10, languages: JSON.stringify(['English', 'Italian', 'Spanish']), specialties: JSON.stringify(['Wine Tours', 'Renaissance Art', 'Cooking Classes']), rating: 4.9, review_count: 156, location: 'Rome, Italy', price_per_day: 280, available: 1 },
    { name: 'Priya Sharma', avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150', email: 'priya@guides.com', phone: '+91-555-0204', bio: 'Yoga instructor and wellness expert guiding spiritual journeys through India. From Himalayan retreats to Kerala backwaters, she creates transformative experiences.', experience: 8, languages: JSON.stringify(['English', 'Hindi', 'Sanskrit']), specialties: JSON.stringify(['Yoga & Wellness', 'Spiritual Tours', 'Ayurveda']), rating: 4.7, review_count: 89, location: 'Rishikesh, India', price_per_day: 150, available: 1 },
    { name: 'James Okafor', avatar: 'https://images.unsplash.com/photo-1463453091185-61582044d556?w=150', email: 'james@guides.com', phone: '+254-555-0205', bio: 'Wildlife biologist and conservationist with extensive knowledge of East African fauna. Expert tracker and photographer for unforgettable safari experiences.', experience: 14, languages: JSON.stringify(['English', 'Swahili', 'French']), specialties: JSON.stringify(['Wildlife Safaris', 'Bird Watching', 'Photography']), rating: 4.9, review_count: 203, location: 'Nairobi, Kenya', price_per_day: 300, available: 1 },
    { name: 'Sofia Andersson', avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150', email: 'sofia@guides.com', phone: '+46-555-0206', bio: 'Arctic explorer and aurora expert based in Swedish Lapland. Dog sledding instructor and ice sculpting artist offering magical winter experiences.', experience: 9, languages: JSON.stringify(['English', 'Swedish', 'German']), specialties: JSON.stringify(['Northern Lights', 'Dog Sledding', 'Arctic Survival']), rating: 4.8, review_count: 112, location: 'Kiruna, Sweden', price_per_day: 275, available: 1 },
    { name: 'Carlos Mendez', avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150', email: 'carlos@guides.com', phone: '+51-555-0207', bio: 'Mountain guide certified in high-altitude trekking across the Andes. Expert in Inca history and Quechua culture with a passion for sustainable tourism.', experience: 11, languages: JSON.stringify(['English', 'Spanish', 'Quechua']), specialties: JSON.stringify(['Trekking', 'Inca History', 'Mountaineering']), rating: 4.8, review_count: 145, location: 'Cusco, Peru', price_per_day: 180, available: 1 },
    { name: 'Fatima Al-Rashid', avatar: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=150', email: 'fatima@guides.com', phone: '+212-555-0208', bio: 'Historian specializing in Islamic architecture and Moroccan culture. Her medina tours uncover hidden riads, secret gardens, and ancient artisan workshops.', experience: 13, languages: JSON.stringify(['English', 'Arabic', 'French', 'Spanish']), specialties: JSON.stringify(['Islamic Architecture', 'Medina Tours', 'Cuisine']), rating: 4.9, review_count: 134, location: 'Marrakech, Morocco', price_per_day: 200, available: 1 },
    { name: 'Hans Mueller', avatar: 'https://images.unsplash.com/photo-1504257432389-52343af06ae3?w=150', email: 'hans@guides.com', phone: '+41-555-0209', bio: 'Alpine mountaineer and ski instructor with 20 years of experience in the Swiss Alps. Specialized in glacier trekking and high-altitude photography.', experience: 20, languages: JSON.stringify(['English', 'German', 'French', 'Italian']), specialties: JSON.stringify(['Skiing', 'Glacier Trek', 'Alpine Photography']), rating: 4.9, review_count: 178, location: 'Zermatt, Switzerland', price_per_day: 320, available: 1 },
    { name: 'Liam O\'Brien', avatar: 'https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?w=150', email: 'liam@guides.com', phone: '+353-555-0210', bio: 'Storyteller and folk historian bringing Irish mythology to life. Expert in Celtic heritage, ancient castles, and the vibrant pub culture of Ireland.', experience: 7, languages: JSON.stringify(['English', 'Irish', 'German']), specialties: JSON.stringify(['Heritage Tours', 'Storytelling', 'Whiskey Tasting']), rating: 4.7, review_count: 87, location: 'Dublin, Ireland', price_per_day: 190, available: 1 },
    { name: 'Aisha Patel', avatar: 'https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?w=150', email: 'aisha@guides.com', phone: '+66-555-0211', bio: 'Marine biologist and diving instructor specializing in Southeast Asian waters. Coral restoration expert and underwater photography guide.', experience: 10, languages: JSON.stringify(['English', 'Thai', 'Malay']), specialties: JSON.stringify(['Diving', 'Marine Biology', 'Island Tours']), rating: 4.8, review_count: 121, location: 'Phuket, Thailand', price_per_day: 175, available: 1 },
    { name: 'Nikolai Petrov', avatar: 'https://images.unsplash.com/photo-1521119989659-a83eee488058?w=150', email: 'nikolai@guides.com', phone: '+7-555-0212', bio: 'Former Bolshoi dancer turned cultural guide. Offers exclusive access to St. Petersburg\'s arts scene, from private ballet rehearsals to Hermitage after-hours tours.', experience: 16, languages: JSON.stringify(['English', 'Russian', 'French']), specialties: JSON.stringify(['Ballet & Arts', 'Imperial History', 'Night Tours']), rating: 4.9, review_count: 167, location: 'St. Petersburg, Russia', price_per_day: 260, available: 1 },
    { name: 'Isabella Cruz', avatar: 'https://images.unsplash.com/photo-1544723795-3fb6469f5b39?w=150', email: 'isabella@guides.com', phone: '+52-555-0213', bio: 'Archaeologist specializing in Mayan and Aztec civilizations. Leads expeditions to hidden ruins and cenotes across Mexico and Central America.', experience: 11, languages: JSON.stringify(['English', 'Spanish', 'Portuguese']), specialties: JSON.stringify(['Archaeology', 'Cenote Diving', 'Indigenous Culture']), rating: 4.8, review_count: 143, location: 'Cancun, Mexico', price_per_day: 195, available: 1 },
    { name: 'Thabo Mbeki', avatar: 'https://images.unsplash.com/photo-1519345182560-3f2917c472ef?w=150', email: 'thabo@guides.com', phone: '+27-555-0214', bio: 'Cultural anthropologist sharing deep knowledge of South African heritage. Township tours, wildlife safaris, and wine country expeditions.', experience: 9, languages: JSON.stringify(['English', 'Zulu', 'Xhosa', 'Afrikaans']), specialties: JSON.stringify(['Cultural Tours', 'Safari', 'Wine Tours']), rating: 4.7, review_count: 98, location: 'Cape Town, South Africa', price_per_day: 210, available: 1 },
    { name: 'Mei Ling Wong', avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150', email: 'meiling@guides.com', phone: '+852-555-0215', bio: 'Street food expert and culinary historian exploring the flavors of Asia. From Hong Kong dim sum to Vietnamese pho, she knows every hidden food stall.', experience: 8, languages: JSON.stringify(['English', 'Cantonese', 'Mandarin', 'Vietnamese']), specialties: JSON.stringify(['Food Tours', 'Market Visits', 'Cooking Classes']), rating: 4.8, review_count: 156, location: 'Hong Kong', price_per_day: 180, available: 1 },
    { name: 'Erik Johansson', avatar: 'https://images.unsplash.com/photo-1509967419530-da38b4704bc6?w=150', email: 'erik@guides.com', phone: '+47-555-0216', bio: 'Viking history expert and fjord cruise specialist. Kayaking guide and northern lights photographer based in Bergen.', experience: 12, languages: JSON.stringify(['English', 'Norwegian', 'Danish']), specialties: JSON.stringify(['Fjord Cruises', 'Viking History', 'Kayaking']), rating: 4.8, review_count: 132, location: 'Bergen, Norway', price_per_day: 240, available: 1 },
    { name: 'Camille Dubois', avatar: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=150', email: 'camille@guides.com', phone: '+33-555-0217', bio: 'Art historian and former Louvre curator. Private museum tours, vineyard visits in Bordeaux, and culinary journeys through Provence.', experience: 14, languages: JSON.stringify(['English', 'French', 'Italian']), specialties: JSON.stringify(['Art History', 'Wine Tours', 'Culinary Journeys']), rating: 4.9, review_count: 189, location: 'Paris, France', price_per_day: 290, available: 1 },
    { name: 'Ahmed Hassan', avatar: 'https://images.unsplash.com/photo-1504829857797-ddff29c27927?w=150', email: 'ahmed@guides.com', phone: '+20-555-0218', bio: 'Egyptologist with 18 years of field experience. Exclusive access to archaeological sites, desert expeditions, and Nile cruise experiences.', experience: 18, languages: JSON.stringify(['English', 'Arabic', 'French', 'German']), specialties: JSON.stringify(['Egyptology', 'Desert Safaris', 'Nile Cruises']), rating: 4.9, review_count: 245, location: 'Cairo, Egypt', price_per_day: 230, available: 1 },
    { name: 'Emma Thompson', avatar: 'https://images.unsplash.com/photo-1489424731084-a5d8b219a5bb?w=150', email: 'emma.t@guides.com', phone: '+44-555-0219', bio: 'Royal history expert and London insider. Buckingham Palace tours, West End theatre experiences, and exclusive shopping in Mayfair.', experience: 10, languages: JSON.stringify(['English', 'French', 'Spanish']), specialties: JSON.stringify(['Royal History', 'Theatre Tours', 'Shopping']), rating: 4.7, review_count: 156, location: 'London, UK', price_per_day: 270, available: 1 },
    { name: 'Ravi Kumar', avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150', email: 'ravi@guides.com', phone: '+66-555-0220', bio: 'Adventure sports specialist in Southeast Asia. Rock climbing, white-water rafting, and jungle trekking expert with safety-first approach.', experience: 9, languages: JSON.stringify(['English', 'Thai', 'Hindi']), specialties: JSON.stringify(['Adventure Sports', 'Rock Climbing', 'Rafting']), rating: 4.7, review_count: 108, location: 'Chiang Mai, Thailand', price_per_day: 165, available: 1 }
  ];

  const insertGuide = db.prepare('INSERT INTO guides (name, avatar, email, phone, bio, experience, languages, specialties, rating, review_count, location, price_per_day, available) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)');
  guides.forEach(g => insertGuide.run(g.name, g.avatar, g.email, g.phone, g.bio, g.experience, g.languages, g.specialties, g.rating, g.review_count, g.location, g.price_per_day, g.available));
  console.log(`Inserted ${guides.length} guides`);

  const reviews = [
    { user_id: 2, destination_id: 1, rating: 5, comment: 'Absolutely magical! The sunset from our villa was the most romantic experience of our lives. The local wine tour was exceptional.' },
    { user_id: 3, destination_id: 1, rating: 4, comment: 'Beautiful island with stunning views. The hotel service was impeccable. Only downside was the crowds in Oia during sunset.' },
    { user_id: 4, destination_id: 2, rating: 5, comment: 'Paradise on Earth! The overwater bungalow was beyond our expectations. Snorkeling with the marine life was unforgettable.' },
    { user_id: 5, destination_id: 2, rating: 5, comment: 'Worth every penny! The private butler service made us feel like royalty. The water is unbelievably clear.' },
    { user_id: 6, destination_id: 3, rating: 4, comment: 'Amazing skiing and the Matterhorn views are breathtaking. The village is charming but quite expensive.' },
    { user_id: 7, destination_id: 3, rating: 5, comment: 'Best ski resort I have ever visited! The après-ski scene is fantastic and the fondue is incredible.' },
    { user_id: 8, destination_id: 4, rating: 5, comment: 'A spiritual journey through beautiful temples and gardens. The tea ceremony was a highlight. Cherry blossoms were stunning!' },
    { user_id: 9, destination_id: 4, rating: 4, comment: 'Rich culture and history everywhere. The bamboo forest walk was serene. Would recommend visiting in spring.' },
    { user_id: 2, destination_id: 5, rating: 5, comment: 'The Great Migration was the most incredible wildlife spectacle I have ever witnessed. Our guide James was phenomenal!' },
    { user_id: 3, destination_id: 5, rating: 5, comment: 'Saw the Big Five on our first day! The luxury tented camp exceeded expectations. Truly a once-in-a-lifetime experience.' },
    { user_id: 4, destination_id: 6, rating: 5, comment: 'Positano is a dream! The coastal drive is thrilling, the food is heavenly, and the views are postcard-perfect.' },
    { user_id: 5, destination_id: 6, rating: 4, comment: 'Gorgeous scenery and amazing Italian cuisine. The steep stairs everywhere can be challenging but worth it.' },
    { user_id: 6, destination_id: 7, rating: 4, comment: 'Ubud is so peaceful and spiritual. The rice terraces are beautiful. Yoga retreat was transformative.' },
    { user_id: 7, destination_id: 7, rating: 5, comment: 'The Balinese people are so warm and welcoming. The spa treatments are world-class and very affordable.' },
    { user_id: 8, destination_id: 8, rating: 5, comment: 'Seeing the Northern Lights from the hot spring was surreal! The ice cave exploration was otherworldly.' },
    { user_id: 9, destination_id: 8, rating: 4, comment: 'Pack warm clothes! The aurora was spectacular but the weather is brutal. Golden Circle tour was amazing.' },
    { user_id: 2, destination_id: 9, rating: 5, comment: 'The medina is a sensory overload in the best way! Our riad was an oasis of calm. The tagine was delicious.' },
    { user_id: 3, destination_id: 9, rating: 4, comment: 'Fascinating culture and beautiful architecture. The desert excursion was a highlight. Be ready to haggle in the souks!' },
    { user_id: 4, destination_id: 10, rating: 5, comment: 'The Great Barrier Reef is even more amazing than photos suggest! Diving among the coral gardens was magical.' },
    { user_id: 5, destination_id: 10, rating: 4, comment: 'Incredible marine life! We saw sea turtles, reef sharks, and countless colorful fish. Cairns is a great base.' },
    { user_id: 6, destination_id: 11, rating: 5, comment: 'Patagonia changed my life. The glaciers, mountains, and wilderness are humbling. Trekking W circuit was challenging but rewarding.' },
    { user_id: 7, destination_id: 11, rating: 5, comment: 'The most beautiful place on Earth! Torres del Paine at sunrise brought tears to my eyes. A must for nature lovers.' },
    { user_id: 8, destination_id: 12, rating: 4, comment: 'Venice is enchanting despite the crowds. Our gondola ride at sunset was incredibly romantic. The gelato is the best in Italy!' },
    { user_id: 9, destination_id: 12, rating: 5, comment: 'Every corner is a work of art. The Murano glass demonstration was fascinating. St. Mark\'s Basilica is awe-inspiring.' },
    { user_id: 2, destination_id: 13, rating: 5, comment: 'Bora Bora redefined luxury for us. Swimming with sharks and rays was thrilling. Mount Otemanu is majestic.' },
    { user_id: 3, destination_id: 13, rating: 5, comment: 'The most romantic honeymoon destination! The lagoon colors are unbelievable. Overwater villa is a must-do.' },
    { user_id: 4, destination_id: 14, rating: 5, comment: 'Inca Trail was challenging but reaching Machu Picchu at sunrise was emotional. Our guide Carlos was incredibly knowledgeable.' },
    { user_id: 5, destination_id: 14, rating: 4, comment: 'The altitude was tough but the scenery is spectacular. Cusco is charming with great food. Book permits early!' },
    { user_id: 6, destination_id: 15, rating: 4, comment: 'Dubai is over-the-top luxury. Burj Khalifa views are incredible. The desert safari with dune bashing was so fun!' },
    { user_id: 7, destination_id: 15, rating: 5, comment: 'Everything is bigger and bolder in Dubai! The shopping malls are entertainment destinations. Fountain show is spectacular.' },
    { user_id: 8, destination_id: 16, rating: 5, comment: 'Petra exceeded all expectations! Walking through the Siq and seeing the Treasury for the first time was magical.' },
    { user_id: 9, destination_id: 16, rating: 5, comment: 'Wadi Rum camping under the stars was unforgettable. Floating in the Dead Sea is a unique experience. Jordan is safe and welcoming.' },
    { user_id: 2, destination_id: 17, rating: 4, comment: 'Adventure capital delivers! Bungee jumping was terrifying but amazing. The scenery is stunning everywhere you look.' },
    { user_id: 3, destination_id: 18, rating: 5, comment: 'Seychelles beaches are the most beautiful I have ever seen! Swimming with giant tortoises on La Digue was incredible.' },
    { user_id: 4, destination_id: 19, rating: 5, comment: 'Lake Louise is even more beautiful in person! The turquoise color looks unreal. Canoeing on the lake is a must.' },
    { user_id: 5, destination_id: 20, rating: 4, comment: 'St. Petersburg is incredibly elegant. The Hermitage could take days to explore. White Nights in June are magical.' },
    { user_id: 6, destination_id: 21, rating: 5, comment: 'Fijian people are the friendliest! The kava ceremony was a unique cultural experience. Coral reefs are pristine.' },
    { user_id: 7, destination_id: 22, rating: 5, comment: 'Hot air balloon over Cappadocia at sunrise - the best travel experience of my life! The cave hotel was so unique.' },
    { user_id: 8, destination_id: 23, rating: 4, comment: 'Hawaii is paradise! The volcano national park was fascinating. Manta ray night snorkel was the highlight.' },
    { user_id: 9, destination_id: 24, rating: 5, comment: 'Sleeping in a glass igloo watching the aurora - nothing compares! Dog sledding was so much fun.' },
    { user_id: 2, destination_id: 25, rating: 5, comment: 'Santorini wine tasting with views of the caldera - perfection! The volcanic wines are unique and delicious.' },
    { user_id: 3, destination_id: 26, rating: 4, comment: 'Rio has incredible energy! Christ the Redeemer is awe-inspiring. Copacabana beach is iconic but crowded.' },
    { user_id: 4, destination_id: 27, rating: 5, comment: 'Zanzibar is exotic and beautiful. Spice tour was so aromatic and interesting. Stone Town has such character.' },
    { user_id: 5, destination_id: 28, rating: 5, comment: 'Norwegian fjords are majestic! The Flam Railway is engineering marvel. Waterfalls everywhere you look.' },
    { user_id: 6, destination_id: 29, rating: 5, comment: 'The Taj Mahal at sunrise is worth the early wake-up. The marble changes colors with the light. Agra Fort is also impressive.' },
    { user_id: 7, destination_id: 30, rating: 4, comment: 'Costa Rica is a nature lover\'s dream! Zip-lining through the cloud forest was exhilarating. Saw so much wildlife.' },
    { user_id: 8, destination_id: 1, rating: 5, comment: 'Second visit to Santorini and it is still my favorite place on Earth. The food, the views, the people - everything is perfect.' },
    { user_id: 9, destination_id: 5, rating: 5, comment: 'Safari changed how I see the world. Being so close to wild animals in their habitat is humbling. Our guide was exceptional.' },
    { user_id: 2, destination_id: 20, rating: 4, comment: 'The ballet at Mariinsky Theatre was world-class. St. Petersburg has such a rich cultural scene. The canals are beautiful.' }
  ];

  const insertReview = db.prepare('INSERT INTO reviews (user_id, destination_id, rating, comment) VALUES (?, ?, ?, ?)');
  reviews.forEach(r => insertReview.run(r.user_id, r.destination_id, r.rating, r.comment));
  console.log(`Inserted ${reviews.length} reviews`);

  const bookings = [
    { user_id: 2, destination_id: 1, booking_date: '2024-12-15', travel_date: '2025-06-15', return_date: '2025-06-22', guests: 2, total_price: 4998, status: 'confirmed', payment_status: 'paid', notes: 'Honeymoon trip, request ocean view villa' },
    { user_id: 3, destination_id: 5, booking_date: '2024-11-20', travel_date: '2025-07-10', return_date: '2025-07-16', guests: 1, total_price: 4599, status: 'confirmed', payment_status: 'paid', notes: 'Photography safari, need early morning departures' },
    { user_id: 4, destination_id: 4, booking_date: '2024-12-01', travel_date: '2025-04-01', return_date: '2025-04-09', guests: 2, total_price: 3798, status: 'confirmed', payment_status: 'paid', notes: 'Cherry blossom season visit' },
    { user_id: 5, destination_id: 2, booking_date: '2024-10-10', travel_date: '2025-02-14', return_date: '2025-02-19', guests: 2, total_price: 7798, status: 'confirmed', payment_status: 'paid', notes: 'Valentine\'s Day getaway' },
    { user_id: 6, destination_id: 6, booking_date: '2024-12-20', travel_date: '2025-09-10', return_date: '2025-09-17', guests: 4, total_price: 11196, status: 'confirmed', payment_status: 'pending', notes: 'Family vacation' },
    { user_id: 7, destination_id: 3, booking_date: '2024-09-15', travel_date: '2025-01-20', return_date: '2025-01-26', guests: 2, total_price: 6598, status: 'completed', payment_status: 'paid', notes: 'Ski trip with lessons' },
    { user_id: 8, destination_id: 14, booking_date: '2024-11-05', travel_date: '2025-08-01', return_date: '2025-08-08', guests: 2, total_price: 4398, status: 'confirmed', payment_status: 'paid', notes: 'Inca Trail trekking, need permits' },
    { user_id: 9, destination_id: 8, booking_date: '2024-08-20', travel_date: '2025-11-15', return_date: '2025-11-20', guests: 2, total_price: 4398, status: 'pending', payment_status: 'pending', notes: 'Northern Lights hunting' },
    { user_id: 2, destination_id: 10, booking_date: '2024-07-12', travel_date: '2025-03-20', return_date: '2025-03-26', guests: 2, total_price: 5798, status: 'completed', payment_status: 'paid', notes: 'Diving certification trip' },
    { user_id: 3, destination_id: 12, booking_date: '2024-12-10', travel_date: '2025-05-01', return_date: '2025-05-06', guests: 1, total_price: 2399, status: 'confirmed', payment_status: 'paid', notes: 'Solo art and culture trip' },
    { user_id: 4, destination_id: 16, booking_date: '2024-06-18', travel_date: '2025-10-10', return_date: '2025-10-16', guests: 2, total_price: 3798, status: 'confirmed', payment_status: 'pending', notes: 'Anniversary trip' },
    { user_id: 5, destination_id: 19, booking_date: '2024-11-25', travel_date: '2025-07-01', return_date: '2025-07-07', guests: 3, total_price: 6897, status: 'confirmed', payment_status: 'paid', notes: 'Family summer vacation' },
    { user_id: 6, destination_id: 22, booking_date: '2024-05-30', travel_date: '2025-09-20', return_date: '2025-09-25', guests: 2, total_price: 2998, status: 'pending', payment_status: 'pending', notes: 'Hot air balloon experience' },
    { user_id: 7, destination_id: 23, booking_date: '2024-10-05', travel_date: '2025-12-15', return_date: '2025-12-22', guests: 2, total_price: 5398, status: 'confirmed', payment_status: 'paid', notes: 'Winter escape' },
    { user_id: 8, destination_id: 25, booking_date: '2024-04-15', travel_date: '2025-08-20', return_date: '2025-08-26', guests: 2, total_price: 4598, status: 'confirmed', payment_status: 'paid', notes: 'Wine and food tour' },
    { user_id: 9, destination_id: 28, booking_date: '2024-12-25', travel_date: '2026-06-01', return_date: '2026-06-08', guests: 2, total_price: 5798, status: 'pending', payment_status: 'pending', notes: 'Fjord cruise and hiking' },
    { user_id: 2, destination_id: 29, booking_date: '2024-03-10', travel_date: '2025-11-01', return_date: '2025-11-06', guests: 1, total_price: 1299, status: 'confirmed', payment_status: 'paid', notes: 'Spiritual journey' },
    { user_id: 3, destination_id: 30, booking_date: '2024-09-01', travel_date: '2025-04-15', return_date: '2025-04-22', guests: 2, total_price: 3798, status: 'completed', payment_status: 'paid', notes: 'Eco-adventure honeymoon' },
    { user_id: 4, destination_id: 17, booking_date: '2024-01-20', travel_date: '2025-12-20', return_date: '2025-12-27', guests: 2, total_price: 5198, status: 'confirmed', payment_status: 'paid', notes: 'Adventure sports vacation' }
  ];

  const insertBooking = db.prepare('INSERT INTO bookings (user_id, destination_id, booking_date, travel_date, return_date, guests, total_price, status, payment_status, notes) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)');
  bookings.forEach(b => insertBooking.run(b.user_id, b.destination_id, b.booking_date, b.travel_date, b.return_date, b.guests, b.total_price, b.status, b.payment_status, b.notes));
  console.log(`Inserted ${bookings.length} bookings`);

  const wishlistItems = [
    { user_id: 2, destination_id: 2 },
    { user_id: 2, destination_id: 5 },
    { user_id: 2, destination_id: 13 },
    { user_id: 3, destination_id: 1 },
    { user_id: 3, destination_id: 4 },
    { user_id: 3, destination_id: 14 },
    { user_id: 4, destination_id: 3 },
    { user_id: 4, destination_id: 7 },
    { user_id: 4, destination_id: 25 },
    { user_id: 5, destination_id: 8 },
    { user_id: 5, destination_id: 15 },
    { user_id: 5, destination_id: 19 },
    { user_id: 6, destination_id: 6 },
    { user_id: 6, destination_id: 9 },
    { user_id: 6, destination_id: 18 },
    { user_id: 7, destination_id: 10 },
    { user_id: 7, destination_id: 11 },
    { user_id: 7, destination_id: 23 },
    { user_id: 8, destination_id: 12 },
    { user_id: 8, destination_id: 20 },
    { user_id: 8, destination_id: 24 },
    { user_id: 9, destination_id: 16 },
    { user_id: 9, destination_id: 21 },
    { user_id: 9, destination_id: 26 },
    { user_id: 2, destination_id: 27 },
    { user_id: 3, destination_id: 28 },
    { user_id: 4, destination_id: 22 },
    { user_id: 5, destination_id: 30 }
  ];

  const insertWishlist = db.prepare('INSERT INTO wishlist (user_id, destination_id) VALUES (?, ?)');
  wishlistItems.forEach(w => {
    try { insertWishlist.run(w.user_id, w.destination_id); } catch(e) {}
  });
  console.log(`Inserted ${wishlistItems.length} wishlist items`);

  const notifications = [
    { user_id: 2, title: 'Booking Confirmed', message: 'Your Santorini Sunset Villas booking has been confirmed for June 15-22, 2025.', type: 'booking' },
    { user_id: 2, title: 'Special Offer', message: 'Get 20% off Maldives packages when you book within the next 7 days!', type: 'offer' },
    { user_id: 3, title: 'Trip Reminder', message: 'Your Kenya Safari is coming up in 2 weeks. Don\'t forget your yellow fever certificate!', type: 'reminder' },
    { user_id: 4, title: 'Booking Confirmed', message: 'Your Kyoto Temple Gardens trip is confirmed for April 1-9, 2025.', type: 'booking' },
    { user_id: 5, title: 'Special Offer', message: 'Early bird discount: Save 15% on Swiss Alps bookings for next winter season.', type: 'offer' },
    { user_id: 6, title: 'Booking Confirmed', message: 'Your Amalfi Coast Luxury vacation has been confirmed.', type: 'booking' },
    { user_id: 7, title: 'Trip Reminder', message: 'Your Machu Picchu trek is in 30 days. Start your altitude training!', type: 'reminder' },
    { user_id: 8, title: 'Booking Confirmed', message: 'Your Iceland Northern Lights adventure is confirmed for November 15-20, 2025.', type: 'booking' },
    { user_id: 9, title: 'Special Offer', message: 'Flash sale: 25% off all Bali packages this week only!', type: 'offer' },
    { user_id: 2, title: 'Trip Reminder', message: 'Your Great Barrier Reef diving trip is in 3 months. Time to book your domestic flights!', type: 'reminder' }
  ];

  const insertNotif = db.prepare('INSERT INTO notifications (user_id, title, message, type) VALUES (?, ?, ?, ?)');
  notifications.forEach(n => insertNotif.run(n.user_id, n.title, n.message, n.type));
  console.log(`Inserted ${notifications.length} notifications`);

  const messages = [
    { sender_id: 2, receiver_id: 1, content: 'Hi Elena! I am planning a trip to Santorini. Do you have availability in June?', read: 1 },
    { sender_id: 1, receiver_id: 2, content: 'Hello Sarah! Yes, I have availability in June. Would you like me to prepare a custom itinerary for you?', read: 1 },
    { sender_id: 2, receiver_id: 1, content: 'That would be wonderful! We are celebrating our anniversary and would love something romantic.', read: 1 },
    { sender_id: 1, receiver_id: 2, content: 'Congratulations! I will prepare a special itinerary with a private sunset dinner and wine tasting tour.', read: 0 },
    { sender_id: 3, receiver_id: 5, content: 'Hi Kenji! I am interested in the tea ceremony experience in Kyoto.', read: 1 },
    { sender_id: 5, receiver_id: 3, content: 'Hello Michael! The tea ceremony is available. I can arrange it at a traditional tea house in Kyoto.', read: 1 },
    { sender_id: 4, receiver_id: 3, content: 'Marco, I would love to do a food tour in Rome. What do you recommend?', read: 1 },
    { sender_id: 3, receiver_id: 4, content: 'Hi Emma! I recommend our Trastevere food tour - authentic Roman cuisine away from the tourist crowds!', read: 0 },
    { sender_id: 5, receiver_id: 1, content: 'Elena, what is the best time to visit the Greek islands for fewer crowds?', read: 1 },
    { sender_id: 1, receiver_id: 5, content: 'Hi Olivia! Late September to early October is perfect - warm weather, calm seas, and much fewer tourists.', read: 0 }
  ];

  const insertMsg = db.prepare('INSERT INTO messages (sender_id, receiver_id, content, read) VALUES (?, ?, ?, ?)');
  messages.forEach(m => insertMsg.run(m.sender_id, m.receiver_id, m.content, m.read));
  console.log(`Inserted ${messages.length} messages`);

  console.log('Database seeded successfully!');
}

module.exports = { seedDatabase };

if (require.main === module) {
  seedDatabase();
}
